@echo off
setlocal EnableExtensions DisableDelayedExpansion
cd /d "%~dp0"
chcp 65001 >nul

set "TUNNEL_CONFIG=%~dp0ssh-tunnel.env.bat"
set "TUNNEL_CONFIG_EXAMPLE=%~dp0ssh-tunnel.env.bat.example"
set "TUNNEL_SCRIPT=%~dp0scripts\ssh_tunnel.ps1"
set "RUNTIME_DIR=%~dp0.runtime"
set "TUNNEL_PID_FILE=%RUNTIME_DIR%\ssh_tunnel.pid"
set "TUNNEL_LOG_FILE=%RUNTIME_DIR%\ssh_tunnel.log"
set "BACKEND_EXIT_CODE=0"
set "TUNNEL_STARTED="

echo ============================================================
echo LLM Relay Desk + vLLM SSH tunnel
echo ============================================================

if not exist "%TUNNEL_SCRIPT%" (
  echo [ERROR] Missing SSH tunnel script:
  echo         %TUNNEL_SCRIPT%
  pause
  exit /b 1
)

if not exist "%TUNNEL_CONFIG%" (
  if not exist "%TUNNEL_CONFIG_EXAMPLE%" (
    echo [ERROR] Missing SSH config template:
    echo         %TUNNEL_CONFIG_EXAMPLE%
    pause
    exit /b 1
  )

  copy /Y "%TUNNEL_CONFIG_EXAMPLE%" "%TUNNEL_CONFIG%" >nul
  echo [ERROR] SSH config file was created:
  echo         %TUNNEL_CONFIG%
  echo.
  echo Edit the jump host, target host, users and key paths.
  echo Then run start.bat again.
  start "" notepad.exe "%TUNNEL_CONFIG%"
  pause
  exit /b 1
)

rem Remove UTF-8 BOM from an older ssh-tunnel.env.bat generated by v1.
set "TUNNEL_CONFIG_FOR_NORMALIZE=%TUNNEL_CONFIG%"
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command ^
  "$p=$env:TUNNEL_CONFIG_FOR_NORMALIZE;" ^
  "$b=[IO.File]::ReadAllBytes($p);" ^
  "if($b.Length-ge3-and$b[0]-eq239-and$b[1]-eq187-and$b[2]-eq191){" ^
  "$t=[Text.Encoding]::UTF8.GetString($b,3,$b.Length-3);" ^
  "[IO.File]::WriteAllText($p,$t,[Text.UTF8Encoding]::new($false))}" ^
  >nul 2>nul
if errorlevel 1 (
  echo [ERROR] Failed to normalize SSH config encoding.
  pause
  exit /b 1
)

call "%TUNNEL_CONFIG%"
if errorlevel 1 (
  echo [ERROR] Failed to load SSH config:
  echo         %TUNNEL_CONFIG%
  echo.
  echo Replace it with ssh-tunnel.env.bat.example if the file is corrupted.
  pause
  exit /b 1
)

where powershell.exe >nul 2>nul
if errorlevel 1 (
  echo [ERROR] Windows PowerShell was not found.
  pause
  exit /b 1
)

where ssh.exe >nul 2>nul
if errorlevel 1 (
  echo [ERROR] Windows OpenSSH client ssh.exe was not found.
  echo Install "OpenSSH Client" from Windows Optional Features.
  pause
  exit /b 1
)

call conda activate ollama
if errorlevel 1 (
  echo [ERROR] Failed to activate conda environment: ollama
  echo Run: conda create -n ollama python=3.12
  pause
  exit /b 1
)

if not exist ".env" copy /Y ".env.example" ".env" >nul

python -c "import fastapi, uvicorn, httpx, dotenv" >nul 2>nul
if errorlevel 1 (
  echo Installing Python dependencies...
  python -m pip install -r requirements.txt
  if errorlevel 1 (
    echo [ERROR] Failed to install Python dependencies.
    pause
    exit /b 1
  )
)

if not exist "%RUNTIME_DIR%" mkdir "%RUNTIME_DIR%" >nul 2>nul

echo.
echo [1/3] Removing a stale project SSH tunnel...
powershell.exe -NoProfile -ExecutionPolicy Bypass ^
  -File "%TUNNEL_SCRIPT%" ^
  -Action Stop ^
  -PidFile "%TUNNEL_PID_FILE%" ^
  -LogFile "%TUNNEL_LOG_FILE%" >nul 2>nul

echo [2/3] Starting the two-hop SSH tunnel...
powershell.exe -NoProfile -ExecutionPolicy Bypass ^
  -File "%TUNNEL_SCRIPT%" ^
  -Action Start ^
  -PidFile "%TUNNEL_PID_FILE%" ^
  -LogFile "%TUNNEL_LOG_FILE%"
if errorlevel 1 (
  echo.
  echo [ERROR] Failed to start SSH tunnel.
  echo Log file: %TUNNEL_LOG_FILE%
  if exist "%TUNNEL_LOG_FILE%" (
    echo ---------------- SSH LOG ----------------
    type "%TUNNEL_LOG_FILE%"
    echo -----------------------------------------
  )
  pause
  exit /b 1
)

set "TUNNEL_STARTED=1"

echo.
echo [3/3] SSH tunnel is ready. Starting LLM Relay Desk...
echo Local vLLM URL: http://127.0.0.1:%SSH_LOCAL_PORT%/v1
echo.

start "" "http://127.0.0.1:11434/ui/"
python app.py
set "BACKEND_EXIT_CODE=%ERRORLEVEL%"

echo.
echo LLM Relay Desk stopped. Closing SSH tunnel...

if defined TUNNEL_STARTED (
  powershell.exe -NoProfile -ExecutionPolicy Bypass ^
    -File "%TUNNEL_SCRIPT%" ^
    -Action Stop ^
    -PidFile "%TUNNEL_PID_FILE%" ^
    -LogFile "%TUNNEL_LOG_FILE%"
)

if not "%BACKEND_EXIT_CODE%"=="0" (
  echo [ERROR] LLM Relay Desk exit code: %BACKEND_EXIT_CODE%
)

pause
exit /b %BACKEND_EXIT_CODE%
