import type { PromptProfiles,TaskIsolationConfig } from '@/types/prompts'
const record=(value:unknown):value is Record<string,unknown>=>typeof value==='object'&&value!==null&&!Array.isArray(value)
async function request(path:string,init?:RequestInit){const response=await fetch(path,{...init,headers:{Accept:'application/json','Content-Type':'application/json',...init?.headers}});const value:unknown=await response.json().catch(()=>null);if(!response.ok){const detail=record(value)&&typeof value.detail==='string'?value.detail:`Request failed with status ${response.status}.`;throw new Error(detail)}return value}
export function parseProfiles(value:unknown):PromptProfiles{if(!record(value)||!record(value.profiles)||!Array.isArray(value.names)||!value.names.every(name=>typeof name==='string')||(value.active!==null&&typeof value.active!=='string'))throw new Error('Malformed prompt profile response.');const profiles:Record<string,string>={};for(const name of value.names){const content=value.profiles[name];if(typeof content!=='string')throw new Error('Malformed prompt profile response.');profiles[name]=content}return{active:value.active,names:[...value.names],profiles}}
export async function getPrompts(){return parseProfiles(await request('/admin/prompts'))}
export async function savePrompt(name:string,content:string){const value=await request(`/admin/prompts/${encodeURIComponent(name)}`,{method:'PUT',body:JSON.stringify({content})});if(!record(value)||value.ok!==true||typeof value.name!=='string')throw new Error('Malformed prompt save response.');return value.name}
export async function activatePrompt(name:string){await request(`/admin/prompts/${encodeURIComponent(name)}/activate`,{method:'POST'})}
export async function deletePrompt(name:string){await request(`/admin/prompts/${encodeURIComponent(name)}`,{method:'DELETE'})}
export function parseTaskConfig(value:unknown):TaskIsolationConfig{if(!record(value))throw new Error('Malformed task isolation response.');return{promptEnabled:value.prompt_enabled!==false,injectionMode:value.prompt_injection_mode==='bannerlord'?'bannerlord':'normal',playerFriendly:value.player_friendly_injection_enabled!==false,playerDialogue:value.enable_player_initiated_dialogue!==false,actionDialogue:value.enable_action_dialogue!==false,npcDialogue:value.enable_npc_initiated_dialogue!==false}}
export async function getTaskConfig(){return parseTaskConfig(await request('/admin/config'))}
export async function saveTaskConfig(config:TaskIsolationConfig){const value=await request('/admin/config',{method:'PUT',body:JSON.stringify({prompt_enabled:config.promptEnabled,prompt_injection_mode:config.injectionMode,player_friendly_injection_enabled:config.playerFriendly,enable_player_initiated_dialogue:config.playerDialogue,enable_action_dialogue:config.actionDialogue,enable_npc_initiated_dialogue:config.npcDialogue})});if(!record(value)||value.ok!==true)return parseTaskConfig(value);return parseTaskConfig(value.config)}
