import { flushPromises, mount } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import ApiTestView from '@/views/ApiTestView.vue'
import { buildRequest } from '@/api/apiTest'
import { createAppI18n } from '@/i18n'
import type { TestRequest } from '@/types/apiTest'

const config={upstream_base_url:'http://127.0.0.1:18000/v1',upstream_protocol:'openai',default_model:'mock/openai-nonstream-usage',request_timeout_seconds:600,native_popup_force_upstream_stream:true,force_reasoning_enabled:true,default_reasoning_effort:'high',prompt_enabled:true,prompt_injection_mode:'bannerlord',debug_logging_enabled:false,debug_log_directory:'debug_logs',debug_log_retention_files:100}
const base:TestRequest={protocol:'openai',model:'mock/model',message:'hello',stream:false,reasoning:true,reasoningEffort:'high',taskType:'player_npc_dialogue',temperature:.7,maxTokens:123}
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}})
const sse=(value:string)=>new Response(value,{headers:{'Content-Type':'text/event-stream'}})
async function render(locale:'en-US'|'zh-CN'='en-US'){const wrapper=mount(ApiTestView,{global:{plugins:[createAppI18n(locale)]}});await flushPromises();return wrapper}
beforeEach(()=>{localStorage.clear();sessionStorage.clear()})

describe('API test request construction',()=>{
  it('builds OpenAI admin request with task and reasoning controls',()=>{const request=buildRequest(base);expect(request.path).toBe('/admin/test-chat');expect(request.body).toMatchObject({max_tokens:123,temperature:.7,reasoning_effort:'high',relay_task_type:'player_npc_dialogue'})})
  it('builds Ollama chat and generate requests',()=>{expect(buildRequest({...base,protocol:'ollama-chat'})).toMatchObject({path:'/api/chat',body:{think:true,options:{temperature:.7,num_predict:123}}});expect(buildRequest({...base,protocol:'ollama-generate'})).toMatchObject({path:'/api/generate',body:{prompt:'hello'}})})
})

describe('API test page',()=>{
  it('loads models and shows connectivity failure',async()=>{const fetch=vi.fn().mockResolvedValueOnce(json(config)).mockResolvedValueOnce(json({ok:true,resolved_protocol:'openai',elapsed_ms:4,response:{data:[{id:'mock/a'}]}})).mockResolvedValueOnce(json({detail:'connectivity failed'},502));vi.stubGlobal('fetch',fetch);const wrapper=await render();await wrapper.get('button').trigger('click');await flushPromises();expect(wrapper.get('datalist option').attributes('value')).toBe('mock/a');expect(wrapper.text()).toContain('1 models');await wrapper.get('button').trigger('click');await flushPromises();expect(wrapper.text()).toContain('connectivity failed')})
  it('renders a non-streaming response and complete payload',async()=>{const body={id:'fixed',choices:[{message:{reasoning_content:'Think',content:'Answer'}}],usage:{prompt_tokens:2,total_tokens:3}};vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(json(config)).mockResolvedValueOnce(json(body)));const wrapper=await render();await wrapper.get('input[type=checkbox]').setValue(false);await wrapper.get('form').trigger('submit');await flushPromises();expect(wrapper.text()).toContain('Think');expect(wrapper.text()).toContain('Answer');expect(wrapper.text()).toContain('"id": "fixed"');expect(localStorage.length).toBe(0);expect(sessionStorage.length).toBe(0)})
  it('renders streaming reasoning, content, and missing usage as unknown',async()=>{const stream='data: {"id":"fixed","choices":[{"delta":{"reasoning_content":"Think"}}]}\n\ndata: {"choices":[{"delta":{"content":"Answer"},"finish_reason":"stop"}]}\n\ndata: [DONE]\n\n';vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(json(config)).mockResolvedValueOnce(sse(stream)));const wrapper=await render();await wrapper.get('form').trigger('submit');await flushPromises();expect(wrapper.text()).toContain('Think');expect(wrapper.text()).toContain('Answer');expect(wrapper.text()).toContain('Usage: Unknown')})
  it('handles reasoning-only and interrupted streams',async()=>{const stream='data: {"choices":[{"delta":{"reasoning_content":"Only reasoning"}}]}\n\n';vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(json(config)).mockResolvedValueOnce(sse(stream)));const wrapper=await render();await wrapper.get('form').trigger('submit');await flushPromises();expect(wrapper.text()).toContain('Only reasoning');expect(wrapper.text()).toContain('Stream interrupted')})
  it('reports malformed SSE',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(json(config)).mockResolvedValueOnce(sse('data: {broken}\n\n')));const wrapper=await render();await wrapper.get('form').trigger('submit');await flushPromises();expect(wrapper.text()).toContain('Malformed SSE response')})
  it.each([401,429,500])('shows HTTP %s errors',async(status)=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(json(config)).mockResolvedValueOnce(json({error:{message:`mock ${status}`}},status)));const wrapper=await render();await wrapper.get('form').trigger('submit');await flushPromises();expect(wrapper.text()).toContain(`${status}: mock ${status}`)})
  it('prevents duplicate submission and cancels the active request',async()=>{let captured:AbortSignal|undefined;const fetch=vi.fn().mockResolvedValueOnce(json(config)).mockImplementationOnce((_url,init)=>{captured=init?.signal;return new Promise((_resolve,reject)=>captured?.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError'))) )});vi.stubGlobal('fetch',fetch);const wrapper=await render();await wrapper.get('form').trigger('submit');await wrapper.get('form').trigger('submit');expect(fetch).toHaveBeenCalledTimes(2);const cancel=wrapper.findAll('button').find(button=>button.text()==='Cancel request')!;await cancel.trigger('click');await flushPromises();expect(captured?.aborted).toBe(true);expect(wrapper.text()).toContain('Ready')})
  it('cleans up an active request on unmount',async()=>{let signal:AbortSignal|undefined;vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(json(config)).mockImplementationOnce((_url,init)=>{signal=init?.signal;return new Promise(()=>{})}));const wrapper=await render();await wrapper.get('form').trigger('submit');wrapper.unmount();expect(signal?.aborted).toBe(true)})
  it('renders Chinese labels',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(json(config)));const wrapper=await render('zh-CN');expect(wrapper.text()).toContain('API 测试');expect(wrapper.text()).toContain('上游连接与模型列表');expect(wrapper.text()).toContain('霸主任务隔离');expect(wrapper.text()).toContain('复制完整响应')})
})
