import{flushPromises,mount}from'@vue/test-utils';import{createMemoryHistory,createRouter}from'vue-router';import{beforeEach,describe,expect,it,vi}from'vitest';import PromptsView from'@/views/PromptsView.vue';import{buildPromptExport,downloadPromptExport,parsePromptImport}from'@/composables/usePromptTransfer';import{createAppI18n}from'@/i18n'
const profiles={active:'First',names:['First','Second'],profiles:{First:'First content',Second:'Second content'}};const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});async function render(locale:'en-US'|'zh-CN'='en-US'){const router=createRouter({history:createMemoryHistory('/ui/'),routes:[{path:'/prompts',component:PromptsView},{path:'/other',component:{template:'<div>other</div>'}}]});await router.push('/prompts');await router.isReady();const wrapper=mount({template:'<RouterView/>'},{global:{plugins:[router,createAppI18n(locale)]}});await flushPromises();return{wrapper,router}}beforeEach(()=>vi.stubGlobal('confirm',vi.fn().mockReturnValue(true)))
describe('prompt profiles',()=>{
it('loads ordered profiles and renders content as plain text',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(json({...profiles,profiles:{...profiles.profiles,First:'<img src=x onerror=alert(1)>'}})));const{wrapper}=await render();expect(wrapper.findAll('.profile-list button').map(item=>item.text())).toEqual(['FirstActive','Second']);expect(wrapper.text()).toContain('<img src=x onerror=alert(1)>');expect(wrapper.find('.plain-preview img').exists()).toBe(false)})
it('creates and edits a profile',async()=>{const fetch=vi.fn().mockResolvedValueOnce(json(profiles)).mockResolvedValueOnce(json({ok:true,name:'Third'})).mockResolvedValueOnce(json({active:'First',names:['First','Second','Third'],profiles:{...profiles.profiles,Third:'New'}}));vi.stubGlobal('fetch',fetch);const{wrapper}=await render();await wrapper.findAll('button').find(b=>b.text()==='New profile')!.trigger('click');await wrapper.get('.prompt-editor input').setValue('Third');await wrapper.get('.prompt-editor textarea').setValue('New');await wrapper.findAll('button').find(b=>b.text()==='Save profile')!.trigger('click');await flushPromises();expect(fetch.mock.calls.some(call=>String(call[0]).includes('/admin/prompts/Third')&&call[1]?.method==='PUT')).toBe(true);expect(wrapper.text()).toContain('Profile saved.')})
it('activates and deletes with confirmation',async()=>{const fetch=vi.fn().mockResolvedValueOnce(json(profiles)).mockResolvedValueOnce(json({ok:true,active:'First'})).mockResolvedValueOnce(json(profiles)).mockResolvedValueOnce(json({ok:true,active:'Second'})).mockResolvedValueOnce(json({active:'Second',names:['Second'],profiles:{Second:'Second content'}}));vi.stubGlobal('fetch',fetch);const{wrapper}=await render();await wrapper.findAll('button').find(b=>b.text()==='Set active')!.trigger('click');await flushPromises();await wrapper.findAll('button').find(b=>b.text()==='Delete profile')!.trigger('click');await flushPromises();expect(confirm).toHaveBeenCalled();expect(fetch.mock.calls.some(call=>call[1]?.method==='DELETE')).toBe(true)})
it('shows backend validation errors',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(json(profiles)).mockResolvedValueOnce(json({detail:'Invalid profile name'},400)));const{wrapper}=await render();await wrapper.get('.prompt-editor textarea').setValue('changed');await wrapper.findAll('button').find(b=>b.text()==='Save profile')!.trigger('click');await flushPromises();expect(wrapper.text()).toContain('Invalid profile name')})
it('protects unsaved route changes',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(json(profiles)));vi.stubGlobal('confirm',vi.fn().mockReturnValue(false));const{wrapper,router}=await render();await wrapper.get('.prompt-editor textarea').setValue('changed');await router.push('/other');expect(router.currentRoute.value.path).toBe('/prompts')})
it('imports validated JSON and rejects invalid JSON',()=>{const bundle=parsePromptImport('{"format_version":1,"active":"A","profiles":[{"id":"A","name":"A","content":"text"}]}','profiles.json');expect(bundle.profiles[0]?.content).toBe('text');expect(()=>parsePromptImport('{bad','profiles.json')).toThrow('Invalid prompt JSON');expect(()=>parsePromptImport('{"format_version":1,"profiles":[{"id":"x","name":"y","content":"z"}]}','profiles.json')).toThrow('Invalid prompt profile entry')})
it('exports in server order and revokes the object URL',()=>{const create=vi.fn().mockReturnValue('blob:test'),revoke=vi.fn();vi.stubGlobal('URL',{...globalThis.URL,createObjectURL:create,revokeObjectURL:revoke});const click=vi.spyOn(globalThis.HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});expect(buildPromptExport(profiles).profiles.map(item=>item.id)).toEqual(['First','Second']);downloadPromptExport(profiles);expect(create).toHaveBeenCalledOnce();expect(click).toHaveBeenCalledOnce();expect(revoke).toHaveBeenCalledWith('blob:test')})
it('renders Chinese',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(json(profiles)));const{wrapper}=await render('zh-CN');expect(wrapper.text()).toContain('提示词配置集');expect(wrapper.text()).toContain('设为当前')})
})
