import { flushPromises, mount } from '@vue/test-utils'
import { createMemoryHistory, createRouter } from 'vue-router'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import SettingsView from '@/views/SettingsView.vue'
import { createAppI18n } from '@/i18n'

const config = { upstream_base_url:'http://127.0.0.1:18000/v1', upstream_protocol:'openai', default_model:'mock/model', request_timeout_seconds:600, native_popup_force_upstream_stream:true, force_reasoning_enabled:false, default_reasoning_effort:'', prompt_enabled:true, debug_logging_enabled:false, debug_log_directory:'debug_logs', debug_log_retention_files:100, upstream_api_key:'', local_api_key:'' }
const statuses = { format_version:1, upstream_api_key:{configured:true,source:'encrypted_file',environment_variable:'UPSTREAM_API_KEY',webui_writable:true}, local_api_key:{configured:true,source:'environment',environment_variable:'LOCAL_API_KEY',webui_writable:false} }
function response(value:unknown,status=200){return new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}})}
async function render(locale:'en-US'|'zh-CN'='en-US') { const router=createRouter({history:createMemoryHistory('/ui/'),routes:[{path:'/settings',component:SettingsView},{path:'/other',component:{template:'<div>other</div>'}}]}); await router.push('/settings'); await router.isReady(); const wrapper=mount({template:'<RouterView />'},{global:{plugins:[router,createAppI18n(locale)]}}); await flushPromises(); return {wrapper,router} }
beforeEach(()=>{ localStorage.clear(); sessionStorage.clear() })

describe('relay settings',()=>{
  it('loads, displays secret state, and saves without duplicate submission',async()=>{ let saveResolve!: (value:Response)=>void; const fetch=vi.fn().mockResolvedValueOnce(response(config)).mockResolvedValueOnce(response(statuses)).mockImplementationOnce(()=>new Promise<Response>(r=>saveResolve=r)).mockResolvedValueOnce(response(statuses)); vi.stubGlobal('fetch',fetch); const {wrapper}=await render(); expect(wrapper.text()).toContain('Encrypted file'); expect(wrapper.text()).toContain('Read-only'); const model=wrapper.findAll('input').find(i=>i.element.value==='mock/model')!; await model.setValue('mock/changed'); await wrapper.get('form').trigger('submit'); await wrapper.get('form').trigger('submit'); expect(fetch.mock.calls.filter(c=>c[1]?.method==='PUT')).toHaveLength(1); saveResolve(response({ok:true,config:{...config,default_model:'mock/changed'}})); await flushPromises(); expect(wrapper.text()).toContain('Configuration saved.') })
  it('shows backend validation errors',async()=>{ const fetch=vi.fn().mockResolvedValueOnce(response(config)).mockResolvedValueOnce(response(statuses)).mockResolvedValueOnce(response({detail:'Server validation failed'},400)); vi.stubGlobal('fetch',fetch); const {wrapper}=await render(); const model=wrapper.findAll('input').find(i=>i.element.value==='mock/model')!; await model.setValue('changed'); await wrapper.get('form').trigger('submit'); await flushPromises(); expect(wrapper.text()).toContain('Server validation failed') })
  it('protects unsaved route changes',async()=>{ vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(response(config)).mockResolvedValueOnce(response(statuses))); vi.stubGlobal('confirm',vi.fn().mockReturnValue(false)); const {wrapper,router}=await render(); const model=wrapper.findAll('input').find(i=>i.element.value==='mock/model')!; await model.setValue('changed'); await router.push('/other'); expect(router.currentRoute.value.path).toBe('/settings'); expect(confirm).toHaveBeenCalled() })
  it('preserves blank secrets and sends a recognized placeholder unchanged',async()=>{ const writable={...statuses,local_api_key:{...statuses.local_api_key,source:'encrypted_file',webui_writable:true}}; const fetch=vi.fn().mockResolvedValueOnce(response(config)).mockResolvedValueOnce(response(writable)).mockResolvedValueOnce(response({ok:true,config})).mockResolvedValueOnce(response(writable)); vi.stubGlobal('fetch',fetch); const {wrapper}=await render(); const secrets=wrapper.findAll('input[type=password]'); await secrets[0]!.setValue('********'); const model=wrapper.findAll('input').find(i=>i.element.value==='mock/model')!; await model.setValue('changed'); await wrapper.get('form').trigger('submit'); await flushPromises(); const call=fetch.mock.calls.find(c=>c[1]?.method==='PUT')!; const payload=JSON.parse(String(call[1]!.body)); expect(payload.upstream_api_key).toBe('********'); expect(payload.local_api_key).toBe('') })
  it('reveals and clears locally without persistence',async()=>{ const writable={...statuses,local_api_key:{...statuses.local_api_key,source:'encrypted_file',webui_writable:true}}; const cleared={...writable,local_api_key:{...writable.local_api_key,configured:false,source:'missing'}}; const fetch=vi.fn().mockResolvedValueOnce(response(config)).mockResolvedValueOnce(response(writable)).mockResolvedValueOnce(response({value:'sk-local-test-only'})).mockResolvedValueOnce(response({ok:true,status:cleared})); vi.stubGlobal('fetch',fetch); vi.stubGlobal('confirm',vi.fn().mockReturnValue(true)); const {wrapper}=await render(); const buttons=wrapper.findAll('button'); await buttons.find(b=>b.text()==='Reveal local key')!.trigger('click'); await flushPromises(); expect(wrapper.text()).toContain('sk-local-test-only'); expect(localStorage.length).toBe(0); expect(sessionStorage.length).toBe(0); const clears=wrapper.findAll('button').filter(b=>b.text()==='Clear'); await clears[clears.length-1]!.trigger('click'); await flushPromises(); expect(wrapper.text()).not.toContain('sk-local-test-only') })
  it('renders Chinese and disables environment secret input',async()=>{ vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(response(config)).mockResolvedValueOnce(response(statuses))); const {wrapper}=await render('zh-CN'); expect(wrapper.text()).toContain('中继设置'); expect(wrapper.text()).toContain('环境变量'); expect(wrapper.findAll('input[type=password]')[1]!.attributes('disabled')).toBeDefined() })
})
