import{flushPromises,mount}from'@vue/test-utils';import{createMemoryHistory,createRouter}from'vue-router';import{afterEach,beforeEach,describe,expect,it,vi}from'vitest';import SubtitlesView from'@/views/SubtitlesView.vue';import{createAppI18n}from'@/i18n'
const raw={native_popup_enabled:true,native_popup_close_seconds:30,native_popup_position:'bottom_center',native_popup_offset_x:1,native_popup_offset_y:2,native_popup_custom_x:120,native_popup_custom_y:130,native_popup_width:960,native_popup_height:220,native_popup_font_size:24,native_popup_font_family:'Segoe UI',native_popup_text_align:'left',native_popup_text_opacity:0.91,native_popup_background_opacity:0.63,native_popup_content_mode:'dialogue',native_popup_dialogue_fields:['response','speech'],native_popup_plain_text_fallback:true,native_popup_force_upstream_stream:true,native_popup_show_reasoning:false,native_popup_click_through:false,native_popup_text_shadow:true,native_popup_shadow_color:'#000000',native_popup_shadow_offset:2,native_popup_text_outline:false,native_popup_outline_color:'#112233',native_popup_outline_width:0,native_popup_background_color:'#101318',native_popup_text_color:'#f7f8fa',native_popup_muted_color:'#aeb6c2',native_popup_border_color:'#343a46',native_popup_error_color:'#ff8f9b'}
function response(value:unknown,status=200){return new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}})}
async function mountView(locale:'en-US'|'zh-CN'='en-US',handler?:(url:string,init?:RequestInit)=>Promise<Response>){const fetch=vi.fn(handler??(async(url:string,init?:RequestInit)=>{if(url.includes('subtitle-fonts'))return response({fonts:['Segoe UI','Manual Font'],platform:'win32'});if(url.includes('preview'))return new Response(new Blob(['png'],{type:'image/png'}));if(url.includes('positioning'))return response({ok:true,request_id:'preview_fixed',positioning:true});if(init?.method==='PUT')return response({ok:true,config:raw});return response(raw)}));vi.stubGlobal('fetch',fetch);const router=createRouter({history:createMemoryHistory(),routes:[{path:'/',component:SubtitlesView}]});await router.push('/');const wrapper=mount(SubtitlesView,{global:{plugins:[router,createAppI18n(locale)]}});await flushPromises();return{wrapper,fetch,router}}
beforeEach(()=>{vi.stubGlobal('URL',{createObjectURL:vi.fn(()=> 'blob:preview'),revokeObjectURL:vi.fn()})});afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals()})
describe('subtitle settings',()=>{
 it('loads all form groups, presets, fonts, exact opacity and colors',async()=>{const{wrapper}=await mountView();expect((wrapper.get('select').element as HTMLSelectElement).value).toBe('bottom_center');expect((wrapper.get('input[list="subtitle-fonts"]').element as HTMLInputElement).value).toBe('Segoe UI');expect(wrapper.text()).toContain('Preset X offset');expect(wrapper.text()).toContain('Custom absolute X');expect(wrapper.text()).toContain('Text opacity');expect(wrapper.text()).toContain('Enable text shadow');expect(wrapper.text()).toContain('Configured dialogue only');const colorInputs=wrapper.findAll('input[pattern]');expect((colorInputs[5]!.element as HTMLInputElement).value).toBe('#112233')})
 it('saves representative settings, preserves dialogue fields, and resets unsaved edits',async()=>{const{wrapper,fetch}=await mountView();await wrapper.get('input[list="subtitle-fonts"]').setValue('Manual Font');const fields=wrapper.findAll('input[type="text"]').find(x=>x.element.getAttribute('pattern')===null&&x.element.getAttribute('list')===null)!;await fields.setValue('response, statement');const checks=wrapper.findAll('input[type="checkbox"]');await checks[checks.length-2]!.setValue(true);await wrapper.get('button.primary-button').trigger('click');await flushPromises();const put=fetch.mock.calls.find(([,i])=>(i as RequestInit|undefined)?.method==='PUT');expect(JSON.parse((put![1] as RequestInit).body as string).native_popup_dialogue_fields).toEqual(['response','statement']);expect(wrapper.text()).toContain('Subtitle settings saved.');await wrapper.get('input[list="subtitle-fonts"]').setValue('Changed');await wrapper.findAll('button').find(b=>b.text()==='Reset changes')!.trigger('click');expect((wrapper.get('input[list="subtitle-fonts"]').element as HTMLInputElement).value).toBe('Segoe UI')})
 it('shows backend validation errors and protects unsaved navigation',async()=>{const{wrapper}=await mountView('en-US',async(url,init)=>{if(url.includes('fonts'))return response({fonts:[]});if(url.includes('preview'))return new Response(new Blob());if(init?.method==='PUT')return response({detail:'Subtitle width is invalid'},400);return response(raw)});await wrapper.get('input[list="subtitle-fonts"]').setValue('Changed');const event=new Event('beforeunload',{cancelable:true});globalThis.window.dispatchEvent(event);expect(event.defaultPrevented).toBe(true);await wrapper.get('button.primary-button').trigger('click');await flushPromises();expect(wrapper.text()).toContain('Subtitle width is invalid')})
 it('refreshes fonts and enters positioning mode without duplicate requests',async()=>{const{wrapper,fetch}=await mountView();await wrapper.findAll('button').find(b=>b.text()==='Refresh installed fonts')!.trigger('click');await wrapper.findAll('button').find(b=>b.text()==='Enter positioning mode')!.trigger('click');await flushPromises();expect(wrapper.text()).toContain('Positioning mode is active');expect(fetch.mock.calls.filter(([u])=>String(u).includes('positioning'))).toHaveLength(1)})
 it('renders Chinese strings',async()=>{const{wrapper}=await mountView('zh-CN');expect(wrapper.text()).toContain('字幕设置');expect(wrapper.text()).toContain('鼠标穿透');expect(wrapper.text()).toContain('高保真预览')})
})
