<script setup lang="ts">
import{computed,onMounted,ref}from'vue';import{useI18n}from'vue-i18n';import{activatePrompt,deletePrompt,getPrompts,savePrompt}from'@/api/prompts';import PromptEditor from'@/components/PromptEditor.vue';import{downloadPromptExport,parsePromptImport}from'@/composables/usePromptTransfer';import{useUnsavedChanges}from'@/composables/useUnsavedChanges';import type{PromptProfiles}from'@/types/prompts'
const{t}=useI18n();const data=ref<PromptProfiles|null>(null),selected=ref(''),name=ref(''),content=ref(''),baseline=ref(''),busy=ref(false),error=ref(''),success=ref(''),importInput=ref<{click():void}|null>(null);const dirty=computed(()=>!!data.value&&JSON.stringify({name:name.value,content:content.value})!==baseline.value);useUnsavedChanges(dirty,()=>t('prompts.unsavedConfirm'))
function select(value:string,force=false){if(!force&&dirty.value&&!globalThis.confirm(t('prompts.unsavedConfirm')))return;selected.value=value;name.value=value;content.value=data.value?.profiles[value]??'';baseline.value=JSON.stringify({name:name.value,content:content.value})}
async function load(preferred?:string){data.value=await getPrompts();select(preferred&&data.value.names.includes(preferred)?preferred:data.value.active??data.value.names[0]??'',true)}
async function run(action:()=>Promise<void>,message:string){if(busy.value)return;busy.value=true;error.value='';success.value='';try{await action();success.value=message}catch(e){error.value=e instanceof Error?e.message:''}finally{busy.value=false}}
async function save(){await run(async()=>{const saved=await savePrompt(name.value.trim(),content.value);await load(saved)},t('prompts.saved'))}async function activate(){await run(async()=>{await activatePrompt(selected.value);await load(selected.value)},t('prompts.activated'))}async function remove(){if(!selected.value||!globalThis.confirm(t('prompts.deleteConfirm')))return;await run(async()=>{await deletePrompt(selected.value);await load()},t('prompts.deleted'))}function create(){if(dirty.value&&!globalThis.confirm(t('prompts.unsavedConfirm')))return;selected.value='';name.value='';content.value='';baseline.value=JSON.stringify({name:'',content:''})}
async function importFile(event:unknown){const input=(event as{target:{files?:ArrayLike<{text():Promise<string>;name:string}>;value:string}}).target,file=input.files?.[0];if(!file)return;try{const bundle=parsePromptImport(await file.text(),file.name);await run(async()=>{for(const profile of bundle.profiles)await savePrompt(profile.name,profile.content);if(bundle.active)await activatePrompt(bundle.active);await load(bundle.active??bundle.profiles[0]?.name)},t('prompts.imported'))}catch(e){error.value=e instanceof Error?e.message:''}finally{input.value=''}}
onMounted(()=>load().catch(e=>error.value=e instanceof Error?e.message:''))
</script>
<template><section class="page prompts-page"><header class="page-heading"><div><p class="eyebrow">{{t('prompts.eyebrow')}}</p><h1>{{t('prompts.title')}}</h1></div><div class="button-row"><button @click="create">{{t('prompts.create')}}</button><button :disabled="!data" @click="data&&downloadPromptExport(data)">{{t('prompts.export')}}</button><button @click="importInput?.click()">{{t('prompts.import')}}</button><input ref="importInput" class="visually-hidden" type="file" accept=".json,.txt,application/json,text/plain" @change="importFile"></div></header><p v-if="error" class="error-text">{{error}}</p><p v-if="success" class="success-text">{{success}}</p><div v-if="data" class="profile-layout"><aside class="profile-list"><button v-for="profile in data.names" :key="profile" :class="{active:profile===selected}" @click="select(profile)"><span>{{profile}}</span><small v-if="profile===data.active">{{t('prompts.active')}}</small></button></aside><section><PromptEditor v-model:name="name" v-model:content="content" :busy="busy" @save="save"/><div class="button-row"><button :disabled="busy||!selected" @click="activate">{{t('prompts.activate')}}</button><button :disabled="busy||!selected" @click="remove">{{t('prompts.delete')}}</button></div><pre class="plain-preview">{{content}}</pre></section></div></section></template>
